### ISSUE TITLE
Unit tests errors

### ISSUE THREAD

**Issue by Mte90** [lucatume/idlikethis#1] opened 2016-04-14 13:34 UTC
I get that errors when I run codeception:
```
1) It_should_be_instantiatable (idlikethis\MetaBoxes\VotesDisplayMetaBoxTest::it_should_be_instantiatable)
                                                            
  [PHPUnit_Framework_Exception] Argument 3 passed to idlikethis_MetaBoxes_VotesDisplayMetaBox::__construct() must be an instance of idlikethis_Texts_VotesMetaBoxTextProviderInterface, instance of Double\stdClass\P60 given, called in /home/www/VVV/www/prova/htdocs/wp-content/plugins/idlikethis/tests/wpunit/idlikethis/MetaBoxes/VotesDisplayMetaBoxTest.php on line 90 and defined
```

```
2) It_should_re (idlikethis\MetaBoxes\VotesDisplayMetaBoxTest::it_should_render_an_empty_message_if_there_are_no_idlikethis_comments_associated_to_the_post)
                                                                                                                                
  [Prophecy\Exception\Doubler\MethodNotFoundException] Method `Double\stdClass\P62::get_empty_comments_text()` is not defined. 
```

```
3) It_ (idlikethis\MetaBoxes\VotesDisplayMetaBoxTest::it_should_render_the_comments_count_display_if_there_are_idlikethis_comments_associated_with_the_post)
                                                                                                                                
  [Prophecy\Exception\Doubler\MethodNotFoundException] Method `Double\stdClass\P64::get_comments_title_text()` is not defined. 
```

```Tests: 89, Assertions: 175, Errors: 3.```

**Comment by lucatume** [comment] 2016-04-18 08:19
I don't get any one of those errors and the errors themselves make no sense: the issue is that the `idlikethis_Texts_VotesMetaBoxTextProviderInterface`

**Comment by Mte90** [comment] 2016-04-18 12:49
Now i get:
```
1) It_should_be_instantiatable (idlikethis\MetaBoxes\VotesDisplayMetaBoxTest::it_should_be_instantiatable)
Failed asserting that false is true.
#1  /home/www/VVV/www/prova/htdocs/wp-content/plugins/idlikethis/tests/wpunit/idlikethis/MetaBoxes/VotesDisplayMetaBoxTest.php:33

---------
2) It_should_render_an_empty_message_if_there_are_no_idlikethis_comments_associated_to (idlikethis\MetaBoxes\VotesDisplayMetaBoxTest::it_should_render_an_empty_message_if_there_are_no_idlikethis_comments_associated_to_the_post)
Failed asserting that false is true.
#1  /home/www/VVV/www/prova/htdocs/wp-content/plugins/idlikethis/tests/wpunit/idlikethis/MetaBoxes/VotesDisplayMetaBoxTest.php:33

---------
3) It_should_render_the_comments_count_display_if_there_are_idlikethis_commen (idlikethis\MetaBoxes\VotesDisplayMetaBoxTest::it_should_render_the_comments_count_display_if_there_are_idlikethis_comments_associated_with_the_post)
Failed asserting that false is true.
#1  /home/www/VVV/www/prova/htdocs/wp-content/plugins/idlikethis/tests/wpunit/idlikethis/MetaBoxes/VotesDisplayMetaBoxTest.php:33
```

**Comment by lucatume** [comment] 2016-08-31 15:47
This proved to be a casing error that I've fixed, closing.

**Closed by lucatume** 2016-08-31 15:47 UTC
